# Generated by Django 5.0.2 on 2024-02-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confPass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shopName', models.CharField(max_length=100)),
                ('shopAddress', models.CharField(max_length=100)),
                ('ShopLicence', models.ImageField(blank=True, upload_to='licence')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('email', models.EmailField(max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('confPass', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
